/**
 * Fetch Snapchat Spotlight page data for a sample of URLs.
 *
 * Reads URLs from data/sample_urls.json (generated by DuckDB query).
 * Fetches each /spotlight/<id> page, extracts __NEXT_DATA__ pageProps.
 *
 * Usage:
 *   npx tsx src/fetch_spotlights.ts              # fetch all
 *   npx tsx src/fetch_spotlights.ts --limit 5    # first 5 only
 *   npx tsx src/fetch_spotlights.ts --status     # print progress
 *   npx tsx src/fetch_spotlights.ts --concurrency 3
 */

import * as fs from "node:fs";
import * as path from "node:path";
import { fileURLToPath } from "node:url";
import { gotScraping } from "got-scraping";

const __dirname = path.dirname(fileURLToPath(import.meta.url));

const DATA_DIR = path.resolve(__dirname, "..", "data");
const URLS_FILE = path.join(DATA_DIR, "sample_urls.json");
const OUT_DIR = path.join(DATA_DIR, "spotlights");
const STATE_FILE = path.join(DATA_DIR, "state.json");
const LOG_FILE = path.join(DATA_DIR, "download_log.jsonl");

const DEFAULT_DELAY_MS = 800;
const DEFAULT_CONCURRENCY = 3;
const REQUEST_TIMEOUT = 20_000;
const NEXT_DATA_RE = /<script[^>]*type="application\/json"[^>]*>(.*?)<\/script>/s;

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

interface SampleUrl {
  url: string;
  source_brand: string;
  source: string;
}

type SpotlightStatus = "fetched" | "not_found" | "rate_limited" | "error";

interface CellState {
  status: SpotlightStatus;
  has_data: boolean;
  fetched_at: string;
  error?: string;
}

interface State {
  cells: Record<string, CellState>;
  total_requests: number;
  total_fetched: number;
  last_updated: string;
}

// ---------------------------------------------------------------------------
// State
// ---------------------------------------------------------------------------

function loadState(): State {
  if (fs.existsSync(STATE_FILE)) return JSON.parse(fs.readFileSync(STATE_FILE, "utf-8"));
  return { cells: {}, total_requests: 0, total_fetched: 0, last_updated: new Date().toISOString() };
}

function saveState(state: State): void {
  state.last_updated = new Date().toISOString();
  fs.writeFileSync(STATE_FILE, JSON.stringify(state, null, 2));
}

function log(level: string, msg: string): void {
  console.log(`[${new Date().toISOString()}] [${level}] ${msg}`);
}

function appendLog(entry: Record<string, unknown>): void {
  fs.appendFileSync(LOG_FILE, JSON.stringify(entry) + "\n");
}

// ---------------------------------------------------------------------------
// Spotlight ID from URL
// ---------------------------------------------------------------------------

function spotlightId(url: string): string {
  const m = url.match(/\/spotlight\/([^?&/]+)/);
  return m ? m[1] : url;
}

function safeFilename(id: string): string {
  return id.replace(/[^a-zA-Z0-9_-]/g, "_").substring(0, 80);
}

// ---------------------------------------------------------------------------
// Core fetch
// ---------------------------------------------------------------------------

interface SpotlightResult {
  status: SpotlightStatus;
  pageProps?: Record<string, unknown>;
  error?: string;
}

async function fetchSpotlight(url: string): Promise<SpotlightResult> {
  let statusCode: number;
  let body: string;
  try {
    const resp = await gotScraping({
      url,
      headerGeneratorOptions: { browsers: ["chrome"], operatingSystems: ["macos"] },
      responseType: "text" as const,
      throwHttpErrors: false,
      timeout: { request: REQUEST_TIMEOUT },
    });
    statusCode = resp.statusCode;
    body = resp.body as string;
  } catch (err) {
    return { status: "error", error: `NETWORK: ${err}` };
  }

  if (statusCode === 404) return { status: "not_found" };
  if (statusCode === 429) return { status: "rate_limited", error: "HTTP 429" };
  if (statusCode !== 200) return { status: "error", error: `HTTP ${statusCode}` };

  const match = NEXT_DATA_RE.exec(body);
  if (!match) {
    if (body.length < 1000) return { status: "rate_limited", error: "Tiny response" };
    return { status: "error", error: "No __NEXT_DATA__" };
  }

  let data: Record<string, unknown>;
  try {
    data = JSON.parse(match[1]);
  } catch {
    return { status: "error", error: "JSON parse failed" };
  }

  const props = data.props as Record<string, unknown> | undefined;
  const pageProps = props?.pageProps as Record<string, unknown> | undefined;
  if (!pageProps) return { status: "error", error: "No pageProps" };

  return { status: "fetched", pageProps };
}

// ---------------------------------------------------------------------------
// Main
// ---------------------------------------------------------------------------

async function main(): Promise<void> {
  const args = process.argv.slice(2);
  const showStatus = args.includes("--status");
  const limitIdx = args.indexOf("--limit");
  const limit = limitIdx >= 0 ? parseInt(args[limitIdx + 1], 10) : Infinity;
  const concIdx = args.indexOf("--concurrency");
  const concurrency = concIdx >= 0 ? parseInt(args[concIdx + 1], 10) : DEFAULT_CONCURRENCY;
  const delayIdx = args.indexOf("--delay");
  const delayMs = delayIdx >= 0 ? parseInt(args[delayIdx + 1], 10) : DEFAULT_DELAY_MS;

  if (!fs.existsSync(URLS_FILE)) {
    console.error(`URL list not found: ${URLS_FILE}\nGenerate it with the DuckDB query first.`);
    process.exit(1);
  }

  const allUrls: SampleUrl[] = JSON.parse(fs.readFileSync(URLS_FILE, "utf-8"));
  const state = loadState();

  fs.mkdirSync(OUT_DIR, { recursive: true });

  if (showStatus) {
    const done = Object.values(state.cells);
    console.log(`\nSpotlight fetch status:`);
    console.log(`  Total URLs:    ${allUrls.length}`);
    console.log(`  Fetched:       ${done.filter((c) => c.status === "fetched").length}`);
    console.log(`  Not found:     ${done.filter((c) => c.status === "not_found").length}`);
    console.log(`  Rate limited:  ${done.filter((c) => c.status === "rate_limited").length}`);
    console.log(`  Errors:        ${done.filter((c) => c.status === "error").length}`);
    console.log(`  Pending:       ${allUrls.length - done.length}`);
    console.log(`  Requests:      ${state.total_requests}\n`);
    process.exit(0);
  }

  let queue = allUrls.filter((u) => !state.cells[u.url]);
  if (limit < queue.length) queue = queue.slice(0, limit);

  if (queue.length === 0) {
    log("INFO", "Nothing to do.");
    process.exit(0);
  }

  log("INFO", `Fetching ${queue.length} spotlights (concurrency: ${concurrency}, delay: ${delayMs}ms)`);

  let fetched = 0;
  let rateLimited = false;

  async function processOne(item: SampleUrl, idx: number): Promise<void> {
    if (rateLimited) return;
    const id = spotlightId(item.url);
    const progress = `[${idx + 1}/${queue.length}]`;

    const t0 = Date.now();
    const result = await fetchSpotlight(item.url);
    const elapsed = Date.now() - t0;
    state.total_requests++;

    appendLog({ ts: new Date().toISOString(), url: item.url, brand: item.source_brand, status: result.status, elapsed_ms: elapsed, error: result.error });

    if (result.status === "fetched" && result.pageProps) {
      const file = path.join(OUT_DIR, `${safeFilename(id)}.json`);
      fs.writeFileSync(file, JSON.stringify({ url: item.url, source_brand: item.source_brand, source: item.source, fetched_at: new Date().toISOString(), pageProps: result.pageProps }, null, 2));
      fetched++;
      state.total_fetched++;
      log("OK", `${progress} ${item.source_brand}: ✓ [${elapsed}ms]`);
    } else if (result.status === "not_found") {
      log("INFO", `${progress} ${item.source_brand}: not found [${elapsed}ms]`);
    } else if (result.status === "rate_limited") {
      log("WARN", `${progress} ${item.source_brand}: RATE LIMITED [${elapsed}ms]`);
      rateLimited = true;
    } else {
      log("ERROR", `${progress} ${item.source_brand}: ${result.error} [${elapsed}ms]`);
    }

    state.cells[item.url] = { status: result.status, has_data: result.status === "fetched", fetched_at: new Date().toISOString(), error: result.error };
  }

  for (let i = 0; i < queue.length && !rateLimited; i += concurrency) {
    const batch = queue.slice(i, i + concurrency);
    await Promise.all(batch.map((item, j) => processOne(item, i + j)));
    saveState(state);
    if (!rateLimited && i + concurrency < queue.length) {
      await new Promise((r) => setTimeout(r, delayMs));
    }
  }

  if (rateLimited) log("WARN", "Rate limited — run again to retry.");
  log("INFO", `Done. Fetched: ${fetched}/${queue.length}, Total requests: ${state.total_requests}`);
}

main().catch((err) => { console.error("Fatal:", err); process.exit(1); });
